language: scala
scala:
- 2.10.6
- 2.11.11
- 2.12.2
- 2.13.0-M5
jdk:
- oraclejdk8
- openjdk7
matrix:
  exclude:
    - scala: 2.12.2
      jdk: openjdk7
    - scala: 2.13.0-M5
      jdk: openjdk7
script:
- sbt ++$TRAVIS_SCALA_VERSION "test-only -- --truncate=999999"
# Tricks to avoid unnecessary cache updates, from
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
