language: scala
jdk:
- oraclejdk8
before_install:
  - git fetch --tags
script:
- sbt ++$TRAVIS_SCALA_VERSION "testOnly -- --truncate=999999"
# Tricks to avoid unnecessary cache updates, from
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
sudo: false
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
    - scala: 2.10.7
    - scala: 2.11.12
    - scala: 2.12.6
    - scala: 2.13.0-RC1
    - stage: release
      script: sbt ci-release
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
